// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OChamaAqui.DATA.Models
{
    public partial class Usuario
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        [Column("cpf")]
        [StringLength(14)]
        public string Cpf { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(50)]
        public string Telefone { get; set; }
        [Required]
        [Column("endereco")]
        [StringLength(50)]
        public string Endereco { get; set; }
        [Required]
        [Column("cidade")]
        [StringLength(50)]
        public string Cidade { get; set; }
        [Required]
        [Column("bairro")]
        [StringLength(50)]
        public string Bairro { get; set; }
        [Required]
        [Column("numero")]
        [StringLength(10)]
        public string Numero { get; set; }
        [Required]
        [Column("estado")]
        [StringLength(10)]
        public string Estado { get; set; }
    }
}