// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OChamaAqui.DATA.Models
{
    [Keyless]
    [Table("Vaga_Cliente")]
    public partial class VagaCliente
    {
        [Column("id")]
        public int Id { get; set; }
        [Column("idVaga")]
        public int IdVaga { get; set; }
        [Column("idUsuario")]
        public int IdUsuario { get; set; }
        [Column("dataAbertura", TypeName = "datetime")]
        public DateTime DataAbertura { get; set; }
        [Column("dataFechamento", TypeName = "datetime")]
        public DateTime DataFechamento { get; set; }

        [ForeignKey("IdUsuario")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
        [ForeignKey("IdVaga")]
        public virtual Vaga IdVagaNavigation { get; set; }
    }
}